# Generated by Django 5.2.6 on 2025-09-09 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0002_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('submit_date', models.DateField(default=datetime.date.today)),
                ('leave_date_from', models.DateField()),
                ('leave_date_to', models.DateField()),
                ('reason', models.CharField(choices=[('ป่วย', 'ป่วย'), ('กิจส่วนตัว', 'กิจส่วนตัว'), ('ลาพักร้อน', 'ลาพักร้อน'), ('อื่นๆ', 'อื่นๆ')], max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='leave_documents/')),
                ('sick_leave_total', models.IntegerField(default=30)),
                ('sick_leave_used', models.IntegerField(default=0)),
                ('absence_leave_total', models.IntegerField(default=30)),
                ('absence_leave_used', models.IntegerField(default=0)),
                ('vacation_leave_total', models.IntegerField(default=15)),
                ('vacation_leave_used', models.IntegerField(default=0)),
                ('status', models.CharField(default='รอดำเนินการ', max_length=20)),
            ],
        ),
    ]
