# Generated by Django 5.2.6 on 2025-09-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0003_leave'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave',
            new_name='Leave_Detail',
        ),
    ]
