# Generated by Django 5.2.6 on 2025-09-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0004_rename_leave_leave_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_detail',
            name='absence_leave_total',
        ),
        migrations.RemoveField(
            model_name='leave_detail',
            name='sick_leave_total',
        ),
        migrations.RemoveField(
            model_name='leave_detail',
            name='vacation_leave_total',
        ),
        migrations.AddField(
            model_name='leave_detail',
            name='absence_leave_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave_detail',
            name='sick_leave_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave_detail',
            name='vacation_leave_remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='absence_leave_total',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='sick_leave_total',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_leave_total',
            field=models.IntegerField(default=15),
        ),
    ]
