# Generated by Django 5.2.6 on 2025-09-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0005_remove_leave_detail_absence_leave_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_detail',
            name='absence_leave_remaining',
        ),
        migrations.RemoveField(
            model_name='leave_detail',
            name='absence_leave_used',
        ),
        migrations.RemoveField(
            model_name='leave_detail',
            name='sick_leave_remaining',
        ),
        migrations.RemoveField(
            model_name='leave_detail',
            name='sick_leave_used',
        ),
        migrations.RemoveField(
            model_name='leave_detail',
            name='vacation_leave_remaining',
        ),
        migrations.RemoveField(
            model_name='leave_detail',
            name='vacation_leave_used',
        ),
        migrations.AddField(
            model_name='user',
            name='absence_leave_remaining',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='absence_leave_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sick_leave_remaining',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='sick_leave_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_leave_remaining',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_leave_used',
            field=models.IntegerField(default=0),
        ),
    ]
