# Generated by Django 5.2.6 on 2025-09-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0006_remove_leave_detail_absence_leave_remaining_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='date_from',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='date_to',
        ),
    ]
