# Generated by Django 5.2.6 on 2025-09-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0008_profile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sick_leave_remaining',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sick_leave_used',
        ),
    ]
