# Generated by Django 5.2.6 on 2025-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0009_remove_profile_sick_leave_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='absence_leave_remaining',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='absence_leave_total',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='absence_leave_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='sick_leave_remaining',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='sick_leave_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='vacation_leave_remaining',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='vacation_leave_total',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='vacation_leave_used',
            field=models.IntegerField(default=0),
        ),
    ]
