# Generated by Django 5.2.6 on 2025-09-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0010_profile_absence_leave_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_detail',
            name='leave_dates_count',
            field=models.IntegerField(default=0),
        ),
    ]
