# Generated by Django 5.2.6 on 2025-09-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0011_leave_detail_leave_dates_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave_detail',
            name='leave_dates_count',
        ),
        migrations.AddField(
            model_name='leave_detail',
            name='leave_days_count',
            field=models.IntegerField(default=0),
        ),
    ]
