# Generated by Django 5.2.6 on 2025-09-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0012_remove_leave_detail_leave_dates_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_detail',
            name='leave_days_count',
            field=models.IntegerField(default=1),
        ),
    ]
