# Generated by Django 5.2.6 on 2025-09-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0013_alter_leave_detail_leave_days_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_detail',
            name='leave_days_count',
            field=models.IntegerField(default=0),
        ),
    ]
