# Generated by Django 5.2.6 on 2025-09-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0014_alter_leave_detail_leave_days_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_detail',
            name='reason',
            field=models.CharField(choices=[('ป่วย', 'ป่วย'), ('กิจส่วนตัว', 'กิจส่วนตัว'), ('ลาพักร้อน', 'ลาพักร้อน')], max_length=50),
        ),
        migrations.AlterField(
            model_name='leave_detail',
            name='status',
            field=models.CharField(choices=[('รอดำเนินการ', 'รอดำเนินการ'), ('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ')], default='รอดำเนินการ', max_length=20),
        ),
    ]
