# Generated by Django 5.2.6 on 2025-09-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0015_alter_leave_detail_reason_alter_leave_detail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
    ]
