# Generated by Django 5.2.6 on 2025-09-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0016_profile_mobile_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_detail',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
